"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.sepa_debit_request import (
    SepaDebitRequest,
)


class BankRequest(object):
    """Implementation of the 'Bank Request' model.

    A Resource representing a request to vault a Bank used for ACH Debit.

    Attributes:
        ach_debit (Any): A Resource representing a request to vault a ACH Debit.
        sepa_debit (SepaDebitRequest): An API resource denoting a request to securely
            store a SEPA Debit.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ach_debit": "ach_debit",
        "sepa_debit": "sepa_debit",
    }

    _optionals = [
        "ach_debit",
        "sepa_debit",
    ]

    def __init__(
        self,
        ach_debit=APIHelper.SKIP,
        sepa_debit=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BankRequest instance."""
        # Initialize members of the class
        if ach_debit is not APIHelper.SKIP:
            self.ach_debit = ach_debit
        if sepa_debit is not APIHelper.SKIP:
            self.sepa_debit = sepa_debit

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ach_debit =\
            dictionary.get("ach_debit")\
            if dictionary.get("ach_debit")\
                else APIHelper.SKIP
        sepa_debit =\
            SepaDebitRequest.from_dictionary(
                dictionary.get("sepa_debit"))\
                if "sepa_debit" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(ach_debit,
                   sepa_debit,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ach_debit=(
            self.ach_debit
            if hasattr(self, "ach_debit")
            else None
        )
        _sepa_debit=(
            self.sepa_debit
            if hasattr(self, "sepa_debit")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ach_debit={_ach_debit!r}, "
            f"sepa_debit={_sepa_debit!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ach_debit=(
            self.ach_debit
            if hasattr(self, "ach_debit")
            else None
        )
        _sepa_debit=(
            self.sepa_debit
            if hasattr(self, "sepa_debit")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ach_debit={_ach_debit!s}, "
            f"sepa_debit={_sepa_debit!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
