"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class CardVerificationProcessorResponse(object):
    """Implementation of the 'Card Verification Processor Response' model.

    The processor response information for payment requests, such as direct credit
    card transactions.

    Attributes:
        avs_code (AvsCode): The address verification code for Visa, Discover,
            Mastercard, or American Express transactions.
        cvv_code (CvvCode): The card verification value code for for Visa, Discover,
            Mastercard, or American Express.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "avs_code": "avs_code",
        "cvv_code": "cvv_code",
    }

    _optionals = [
        "avs_code",
        "cvv_code",
    ]

    def __init__(
        self,
        avs_code=APIHelper.SKIP,
        cvv_code=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CardVerificationProcessorResponse instance."""
        # Initialize members of the class
        if avs_code is not APIHelper.SKIP:
            self.avs_code = avs_code
        if cvv_code is not APIHelper.SKIP:
            self.cvv_code = cvv_code

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        avs_code =\
            dictionary.get("avs_code")\
            if dictionary.get("avs_code")\
                else APIHelper.SKIP
        cvv_code =\
            dictionary.get("cvv_code")\
            if dictionary.get("cvv_code")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(avs_code,
                   cvv_code,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _avs_code=(
            self.avs_code
            if hasattr(self, "avs_code")
            else None
        )
        _cvv_code=(
            self.cvv_code
            if hasattr(self, "cvv_code")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"avs_code={_avs_code!r}, "
            f"cvv_code={_cvv_code!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _avs_code=(
            self.avs_code
            if hasattr(self, "avs_code")
            else None
        )
        _cvv_code=(
            self.cvv_code
            if hasattr(self, "cvv_code")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"avs_code={_avs_code!s}, "
            f"cvv_code={_cvv_code!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
