"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.three_d_secure_card_authentication_response import (
    ThreeDSecureCardAuthenticationResponse,
)


class CardAuthenticationResponse(object):
    """Implementation of the 'Card Authentication Response' model.

    Results of Authentication such as 3D Secure.

    Attributes:
        three_d_secure (ThreeDSecureCardAuthenticationResponse): Results of 3D Secure
            Authentication.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "three_d_secure": "three_d_secure",
    }

    _optionals = [
        "three_d_secure",
    ]

    def __init__(
        self,
        three_d_secure=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CardAuthenticationResponse instance."""
        # Initialize members of the class
        if three_d_secure is not APIHelper.SKIP:
            self.three_d_secure = three_d_secure

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        three_d_secure =\
            ThreeDSecureCardAuthenticationResponse.from_dictionary(
                dictionary.get("three_d_secure"))\
                if "three_d_secure" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(three_d_secure,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _three_d_secure=(
            self.three_d_secure
            if hasattr(self, "three_d_secure")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"three_d_secure={_three_d_secure!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _three_d_secure=(
            self.three_d_secure
            if hasattr(self, "three_d_secure")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"three_d_secure={_three_d_secure!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
