from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel


class CustomerResponse(SdkBaseModel):
    """Customer in merchant's or partner's system of records."""

    id: Optional[str] = UNSET
    """The unique ID for a customer generated by PayPal."""

    merchant_customer_id: Optional[str] = UNSET
    """Merchants and partners may already have a data-store where their customer information is persisted. Use
    merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer."""


class CustomerResponseDict(TypedDict):
    id: NotRequired[str]
    merchant_customer_id: NotRequired[str]
