"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.experience_context import (
    ExperienceContext,
)


class EpsPaymentRequest(object):
    """Implementation of the 'EPS Payment Request' model.

    Information needed to pay using eps.

    Attributes:
        name (str): The full name representation like Mr J Smith.
        country_code (str): The [two-character ISO 3166-1
            code](https://developer.paypal.com/api/rest/reference/country-codes/)
            that identifies the country or region. Note: The country code for Great
            Britain is GB and not UK as used in the top-level domain names for that
            country. Use the `C2` country code for China worldwide for comparable
            uncontrolled price (CUP) method, bank card, and cross-border transactions.
        experience_context (ExperienceContext): Customizes the payer experience
            during the approval process for the payment.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "country_code": "country_code",
        "experience_context": "experience_context",
    }

    _optionals = [
        "experience_context",
    ]

    def __init__(
        self,
        name=None,
        country_code=None,
        experience_context=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EpsPaymentRequest instance."""
        # Initialize members of the class
        self.name = name
        self.country_code = country_code
        if experience_context is not APIHelper.SKIP:
            self.experience_context = experience_context

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        country_code =\
            dictionary.get("country_code")\
            if dictionary.get("country_code")\
                else None
        experience_context =\
            ExperienceContext.from_dictionary(
                dictionary.get("experience_context"))\
                if "experience_context" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   country_code,
                   experience_context,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _country_code=self.country_code
        _experience_context=(
            self.experience_context
            if hasattr(self, "experience_context")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"country_code={_country_code!r}, "
            f"experience_context={_experience_context!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _country_code=self.country_code
        _experience_context=(
            self.experience_context
            if hasattr(self, "experience_context")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"country_code={_country_code!s}, "
            f"experience_context={_experience_context!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
