"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.link_description import LinkDescription


class ErrorDetails(object):
    """Implementation of the 'Error Details' model.

    The error details. Required for client-side `4XX` errors.

    Attributes:
        field (str): The field that caused the error. If this field is in the body,
            set this value to the field's JSON pointer value. Required for
            client-side errors.
        value (str): The value of the field that caused the error.
        location (str): The location of the field that caused the error. Value is
            `body`, `path`, or `query`.
        issue (str): The unique, fine-grained application-level error code.
        description (str): The human-readable description for an issue. The
            description can change over the lifetime of an API, so clients must not
            depend on this value.
        links (List[LinkDescription]): An array of request-related [HATEOAS
            links](https://developer.paypal.com/api/rest/responses/#hateoas-links)
            that are either relevant to the issue by providing additional information
            or offering potential resolutions.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "issue": "issue",
        "field": "field",
        "value": "value",
        "location": "location",
        "description": "description",
        "links": "links",
    }

    _optionals = [
        "field",
        "value",
        "location",
        "description",
        "links",
    ]

    def __init__(
        self,
        issue=None,
        field=APIHelper.SKIP,
        value=APIHelper.SKIP,
        location="body",
        description=APIHelper.SKIP,
        links=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ErrorDetails instance."""
        # Initialize members of the class
        if field is not APIHelper.SKIP:
            self.field = field
        if value is not APIHelper.SKIP:
            self.value = value
        self.location = location
        self.issue = issue
        if description is not APIHelper.SKIP:
            self.description = description
        if links is not APIHelper.SKIP:
            self.links = links

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        issue =\
            dictionary.get("issue")\
            if dictionary.get("issue")\
                else None
        field =\
            dictionary.get("field")\
            if dictionary.get("field")\
                else APIHelper.SKIP
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else APIHelper.SKIP
        location =\
            dictionary.get("location")\
            if dictionary.get("location")\
                else "body"
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        links = None
        if dictionary.get("links") is not None:
            links = [
                LinkDescription.from_dictionary(x)
                    for x in dictionary.get("links")
            ]
        else:
            links = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(issue,
                   field,
                   value,
                   location,
                   description,
                   links,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _value=(
            self.value
            if hasattr(self, "value")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _issue=self.issue
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"field={_field!r}, "
            f"value={_value!r}, "
            f"location={_location!r}, "
            f"issue={_issue!r}, "
            f"description={_description!r}, "
            f"links={_links!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _value=(
            self.value
            if hasattr(self, "value")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _issue=self.issue
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"field={_field!s}, "
            f"value={_value!s}, "
            f"location={_location!s}, "
            f"issue={_issue!s}, "
            f"description={_description!s}, "
            f"links={_links!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
