"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.money import Money
from paypal.models.plan_override import PlanOverride
from paypal.models.shipping_details import ShippingDetails
from paypal.models.subscription_patch_application_context import (
    SubscriptionPatchApplicationContext,
)


class ModifySubscriptionRequest(object):
    """Implementation of the 'Modify Subscription Request' model.

    The request to update the quantity of the product or service in a subscription.
    You can also use this method to switch the plan and update the `shipping_amount`
    and `shipping_address` values for the subscription. This type of update requires
    the buyer's consent.

    Attributes:
        plan_id (str): The unique PayPal-generated ID for the plan.
        quantity (str): The quantity of the product or service in the subscription.
        shipping_amount (Money): The currency and amount for a financial transaction,
            such as a balance or payment due.
        shipping_address (ShippingDetails): The shipping details.
        application_context (SubscriptionPatchApplicationContext): The application
            context, which customizes the payer experience during the subscription
            approval process with PayPal.
        plan (PlanOverride): An inline plan object to customise the subscription. You
            can override plan level default attributes by providing customised values
            for the subscription in this object.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "plan_id": "plan_id",
        "quantity": "quantity",
        "shipping_amount": "shipping_amount",
        "shipping_address": "shipping_address",
        "application_context": "application_context",
        "plan": "plan",
    }

    _optionals = [
        "plan_id",
        "quantity",
        "shipping_amount",
        "shipping_address",
        "application_context",
        "plan",
    ]

    def __init__(
        self,
        plan_id=APIHelper.SKIP,
        quantity=APIHelper.SKIP,
        shipping_amount=APIHelper.SKIP,
        shipping_address=APIHelper.SKIP,
        application_context=APIHelper.SKIP,
        plan=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ModifySubscriptionRequest instance."""
        # Initialize members of the class
        if plan_id is not APIHelper.SKIP:
            self.plan_id = plan_id
        if quantity is not APIHelper.SKIP:
            self.quantity = quantity
        if shipping_amount is not APIHelper.SKIP:
            self.shipping_amount = shipping_amount
        if shipping_address is not APIHelper.SKIP:
            self.shipping_address = shipping_address
        if application_context is not APIHelper.SKIP:
            self.application_context = application_context
        if plan is not APIHelper.SKIP:
            self.plan = plan

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        plan_id =\
            dictionary.get("plan_id")\
            if dictionary.get("plan_id")\
                else APIHelper.SKIP
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else APIHelper.SKIP
        shipping_amount =\
            Money.from_dictionary(
                dictionary.get("shipping_amount"))\
                if "shipping_amount" in dictionary.keys()\
                else APIHelper.SKIP
        shipping_address =\
            ShippingDetails.from_dictionary(
                dictionary.get("shipping_address"))\
                if "shipping_address" in dictionary.keys()\
                else APIHelper.SKIP
        application_context =\
            SubscriptionPatchApplicationContext.from_dictionary(
                dictionary.get("application_context"))\
                if "application_context" in dictionary.keys()\
                else APIHelper.SKIP
        plan =\
            PlanOverride.from_dictionary(
                dictionary.get("plan"))\
                if "plan" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(plan_id,
                   quantity,
                   shipping_amount,
                   shipping_address,
                   application_context,
                   plan,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _quantity=(
            self.quantity
            if hasattr(self, "quantity")
            else None
        )
        _shipping_amount=(
            self.shipping_amount
            if hasattr(self, "shipping_amount")
            else None
        )
        _shipping_address=(
            self.shipping_address
            if hasattr(self, "shipping_address")
            else None
        )
        _application_context=(
            self.application_context
            if hasattr(self, "application_context")
            else None
        )
        _plan=(
            self.plan
            if hasattr(self, "plan")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"plan_id={_plan_id!r}, "
            f"quantity={_quantity!r}, "
            f"shipping_amount={_shipping_amount!r}, "
            f"shipping_address={_shipping_address!r}, "
            f"application_context={_application_context!r}, "
            f"plan={_plan!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _quantity=(
            self.quantity
            if hasattr(self, "quantity")
            else None
        )
        _shipping_amount=(
            self.shipping_amount
            if hasattr(self, "shipping_amount")
            else None
        )
        _shipping_address=(
            self.shipping_address
            if hasattr(self, "shipping_address")
            else None
        )
        _application_context=(
            self.application_context
            if hasattr(self, "application_context")
            else None
        )
        _plan=(
            self.plan
            if hasattr(self, "plan")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"plan_id={_plan_id!s}, "
            f"quantity={_quantity!s}, "
            f"shipping_amount={_shipping_amount!s}, "
            f"shipping_address={_shipping_address!s}, "
            f"application_context={_application_context!s}, "
            f"plan={_plan!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
