"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class Money(object):
    """Implementation of the 'Money' model.

    The currency and amount for a financial transaction, such as a balance or payment
    due.

    Attributes:
        currency_code (str): The [three-character ISO-4217 currency
            code](https://developer.paypal.com/api/rest/reference/currency-codes/)
            that identifies the currency.
        value (str): The value, which might be: An integer for currencies like `JPY`
            that are not typically fractional. A decimal fraction for currencies like
            `TND` that are subdivided into thousandths. For the required number of
            decimal places for a currency code, see [Currency
            Codes](https://developer.paypal.com/api/rest/reference/currency-codes/).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "currency_code": "currency_code",
        "value": "value",
    }

    def __init__(
        self,
        currency_code=None,
        value=None,
        additional_properties=None):
        """Initialize a Money instance."""
        # Initialize members of the class
        self.currency_code = currency_code
        self.value = value

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        currency_code =\
            dictionary.get("currency_code")\
            if dictionary.get("currency_code")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(currency_code,
                   value,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _currency_code=self.currency_code
        _value=self.value
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"currency_code={_currency_code!r}, "
            f"value={_value!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _currency_code=self.currency_code
        _value=self.value
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"currency_code={_currency_code!s}, "
            f"value={_value!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
