"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.apple_pay_request import (
    ApplePayRequest,
)
from paypal.models.card_request import CardRequest
from paypal.models.google_pay_request import (
    GooglePayRequest,
)
from paypal.models.pay_pal_wallet import PayPalWallet
from paypal.models.token import Token
from paypal.models.venmo_wallet_request import (
    VenmoWalletRequest,
)


class OrderAuthorizeRequestPaymentSource(object):
    """Implementation of the 'Order Authorize Request Payment Source' model.

    The payment source definition.

    Attributes:
        card (CardRequest): The payment card to use to fund a payment. Can be a
            credit or debit card. Note: Passing card number, cvv and expiry directly
            via the API requires PCI SAQ D compliance. *PayPal offers a mechanism by
            which you do not have to take on the PCI SAQ D burden by using hosted
            fields - refer to this Integration Guide*.
        token (Token): The tokenized payment source to fund a payment.
        paypal (PayPalWallet): A resource that identifies a PayPal Wallet is used for
            payment.
        apple_pay (ApplePayRequest): Information needed to pay using ApplePay.
        google_pay (GooglePayRequest): Information needed to pay using Google Pay.
        venmo (VenmoWalletRequest): Information needed to pay using Venmo.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "card": "card",
        "token": "token",
        "paypal": "paypal",
        "apple_pay": "apple_pay",
        "google_pay": "google_pay",
        "venmo": "venmo",
    }

    _optionals = [
        "card",
        "token",
        "paypal",
        "apple_pay",
        "google_pay",
        "venmo",
    ]

    def __init__(
        self,
        card=APIHelper.SKIP,
        token=APIHelper.SKIP,
        paypal=APIHelper.SKIP,
        apple_pay=APIHelper.SKIP,
        google_pay=APIHelper.SKIP,
        venmo=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OrderAuthorizeRequestPaymentSource instance."""
        # Initialize members of the class
        if card is not APIHelper.SKIP:
            self.card = card
        if token is not APIHelper.SKIP:
            self.token = token
        if paypal is not APIHelper.SKIP:
            self.paypal = paypal
        if apple_pay is not APIHelper.SKIP:
            self.apple_pay = apple_pay
        if google_pay is not APIHelper.SKIP:
            self.google_pay = google_pay
        if venmo is not APIHelper.SKIP:
            self.venmo = venmo

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        card =\
            CardRequest.from_dictionary(
                dictionary.get("card"))\
                if "card" in dictionary.keys()\
                else APIHelper.SKIP
        token =\
            Token.from_dictionary(
                dictionary.get("token"))\
                if "token" in dictionary.keys()\
                else APIHelper.SKIP
        paypal =\
            PayPalWallet.from_dictionary(
                dictionary.get("paypal"))\
                if "paypal" in dictionary.keys()\
                else APIHelper.SKIP
        apple_pay =\
            ApplePayRequest.from_dictionary(
                dictionary.get("apple_pay"))\
                if "apple_pay" in dictionary.keys()\
                else APIHelper.SKIP
        google_pay =\
            GooglePayRequest.from_dictionary(
                dictionary.get("google_pay"))\
                if "google_pay" in dictionary.keys()\
                else APIHelper.SKIP
        venmo =\
            VenmoWalletRequest.from_dictionary(
                dictionary.get("venmo"))\
                if "venmo" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(card,
                   token,
                   paypal,
                   apple_pay,
                   google_pay,
                   venmo,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _paypal=(
            self.paypal
            if hasattr(self, "paypal")
            else None
        )
        _apple_pay=(
            self.apple_pay
            if hasattr(self, "apple_pay")
            else None
        )
        _google_pay=(
            self.google_pay
            if hasattr(self, "google_pay")
            else None
        )
        _venmo=(
            self.venmo
            if hasattr(self, "venmo")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!r}, "
            f"token={_token!r}, "
            f"paypal={_paypal!r}, "
            f"apple_pay={_apple_pay!r}, "
            f"google_pay={_google_pay!r}, "
            f"venmo={_venmo!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _paypal=(
            self.paypal
            if hasattr(self, "paypal")
            else None
        )
        _apple_pay=(
            self.apple_pay
            if hasattr(self, "apple_pay")
            else None
        )
        _google_pay=(
            self.google_pay
            if hasattr(self, "google_pay")
            else None
        )
        _venmo=(
            self.venmo
            if hasattr(self, "venmo")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!s}, "
            f"token={_token!s}, "
            f"paypal={_paypal!s}, "
            f"apple_pay={_apple_pay!s}, "
            f"google_pay={_google_pay!s}, "
            f"venmo={_venmo!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
