"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.cobranded_card import CobrandedCard
from paypal.models.pay_pal_wallet_vault_response import (
    PayPalWalletVaultResponse,
)


class PayPalWalletAttributesResponse(object):
    """Implementation of the 'PayPal Wallet Attributes Response' model.

    Additional attributes associated with the use of a PayPal Wallet.

    Attributes:
        vault (PayPalWalletVaultResponse): The details about a saved PayPal Wallet
            payment source.
        cobranded_cards (List[CobrandedCard]): An array of merchant cobranded cards
            used by buyer to complete an order. This array will be present if a
            merchant has onboarded their cobranded card with PayPal and provided
            corresponding label(s).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "vault": "vault",
        "cobranded_cards": "cobranded_cards",
    }

    _optionals = [
        "vault",
        "cobranded_cards",
    ]

    def __init__(
        self,
        vault=APIHelper.SKIP,
        cobranded_cards=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PayPalWalletAttributesResponse instance."""
        # Initialize members of the class
        if vault is not APIHelper.SKIP:
            self.vault = vault
        if cobranded_cards is not APIHelper.SKIP:
            self.cobranded_cards = cobranded_cards

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        vault =\
            PayPalWalletVaultResponse.from_dictionary(
                dictionary.get("vault"))\
                if "vault" in dictionary.keys()\
                else APIHelper.SKIP
        cobranded_cards = None
        if dictionary.get("cobranded_cards") is not None:
            cobranded_cards = [
                CobrandedCard.from_dictionary(x)
                    for x in dictionary.get("cobranded_cards")
            ]
        else:
            cobranded_cards = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(vault,
                   cobranded_cards,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _vault=(
            self.vault
            if hasattr(self, "vault")
            else None
        )
        _cobranded_cards=(
            self.cobranded_cards
            if hasattr(self, "cobranded_cards")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"vault={_vault!r}, "
            f"cobranded_cards={_cobranded_cards!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _vault=(
            self.vault
            if hasattr(self, "vault")
            else None
        )
        _cobranded_cards=(
            self.cobranded_cards
            if hasattr(self, "cobranded_cards")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"vault={_vault!s}, "
            f"cobranded_cards={_cobranded_cards!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
