from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel
from .name import Name, NameDict
from .phone_with_type import PhoneWithType, PhoneWithTypeDict


class PayPalWalletCustomerRequest(SdkBaseModel):
    id: Optional[str] = UNSET
    """The unique ID for a customer generated by PayPal."""

    email_address: Optional[str] = UNSET
    """The internationalized email address. Note: Up to 64 characters are allowed before and 255 characters are allowed
    after the @ sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern
    verifies that an unquoted @ sign exists."""

    phone: Optional[PhoneWithType] = UNSET
    """The phone information."""

    name: Optional[Name] = UNSET
    """The name of the party."""

    merchant_customer_id: Optional[str] = UNSET
    """Merchants and partners may already have a data-store where their customer information is persisted. Use
    merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer."""


class PayPalWalletCustomerRequestDict(TypedDict):
    id: NotRequired[str]
    email_address: NotRequired[str]
    phone: NotRequired[PhoneWithType | PhoneWithTypeDict]
    name: NotRequired[Name | NameDict]
    merchant_customer_id: NotRequired[str]
