"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class PayeeBase(object):
    """Implementation of the 'Payee Base' model.

    The details for the merchant who receives the funds and fulfills the order. The
    merchant is also known as the payee.

    Attributes:
        email_address (str): The internationalized email address. Note: Up to 64
            characters are allowed before and 255 characters are allowed after the @
            sign. However, the generally accepted maximum length for an email address
            is 254 characters. The pattern verifies that an unquoted @ sign exists.
        merchant_id (str): The account identifier for a PayPal account.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email_address": "email_address",
        "merchant_id": "merchant_id",
    }

    _optionals = [
        "email_address",
        "merchant_id",
    ]

    def __init__(
        self,
        email_address=APIHelper.SKIP,
        merchant_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PayeeBase instance."""
        # Initialize members of the class
        if email_address is not APIHelper.SKIP:
            self.email_address = email_address
        if merchant_id is not APIHelper.SKIP:
            self.merchant_id = merchant_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        email_address =\
            dictionary.get("email_address")\
            if dictionary.get("email_address")\
                else APIHelper.SKIP
        merchant_id =\
            dictionary.get("merchant_id")\
            if dictionary.get("merchant_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(email_address,
                   merchant_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _email_address=(
            self.email_address
            if hasattr(self, "email_address")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email_address={_email_address!r}, "
            f"merchant_id={_merchant_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _email_address=(
            self.email_address
            if hasattr(self, "email_address")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email_address={_email_address!s}, "
            f"merchant_id={_merchant_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
