"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.payment_token_request_card import (
    PaymentTokenRequestCard,
)
from paypal.models.vault_token_request import (
    VaultTokenRequest,
)


class PaymentTokenRequestPaymentSource(object):
    """Implementation of the 'Payment Token Request Payment Source' model.

    The payment method to vault with the instrument details.

    Attributes:
        card (PaymentTokenRequestCard): A Resource representing a request to vault a
            Card.
        token (VaultTokenRequest): The Tokenized Payment Source representing a
            Request to Vault a Token.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "card": "card",
        "token": "token",
    }

    _optionals = [
        "card",
        "token",
    ]

    def __init__(
        self,
        card=APIHelper.SKIP,
        token=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentTokenRequestPaymentSource instance."""
        # Initialize members of the class
        if card is not APIHelper.SKIP:
            self.card = card
        if token is not APIHelper.SKIP:
            self.token = token

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        card =\
            PaymentTokenRequestCard.from_dictionary(
                dictionary.get("card"))\
                if "card" in dictionary.keys()\
                else APIHelper.SKIP
        token =\
            VaultTokenRequest.from_dictionary(
                dictionary.get("token"))\
                if "token" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(card,
                   token,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!r}, "
            f"token={_token!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!s}, "
            f"token={_token!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
