"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.customer_response import (
    CustomerResponse,
)
from paypal.models.link_description import LinkDescription
from paypal.models.payment_token_response_payment_source import (
    PaymentTokenResponsePaymentSource,
)


class PaymentTokenResponse(object):
    """Implementation of the 'Payment Token Response' model.

    Full representation of a saved payment token.

    Attributes:
        id (str): The PayPal-generated ID for the vaulted payment source. This ID
            should be stored on the merchant's server so the saved payment source can
            be used for future transactions.
        customer (CustomerResponse): Customer in merchant's or partner's system of
            records.
        payment_source (PaymentTokenResponsePaymentSource): The vaulted payment
            method details.
        links (List[LinkDescription]): An array of related [HATEOAS
            links](https://developer.paypal.com/api/rest/responses/#hateoas).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "customer": "customer",
        "payment_source": "payment_source",
        "links": "links",
    }

    _optionals = [
        "id",
        "customer",
        "payment_source",
        "links",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        customer=APIHelper.SKIP,
        payment_source=APIHelper.SKIP,
        links=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PaymentTokenResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if customer is not APIHelper.SKIP:
            self.customer = customer
        if payment_source is not APIHelper.SKIP:
            self.payment_source = payment_source
        if links is not APIHelper.SKIP:
            self.links = links

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        customer =\
            CustomerResponse.from_dictionary(
                dictionary.get("customer"))\
                if "customer" in dictionary.keys()\
                else APIHelper.SKIP
        payment_source =\
            PaymentTokenResponsePaymentSource.from_dictionary(
                dictionary.get("payment_source"))\
                if "payment_source" in dictionary.keys()\
                else APIHelper.SKIP
        links = None
        if dictionary.get("links") is not None:
            links = [
                LinkDescription.from_dictionary(x)
                    for x in dictionary.get("links")
            ]
        else:
            links = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   customer,
                   payment_source,
                   links,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _customer=(
            self.customer
            if hasattr(self, "customer")
            else None
        )
        _payment_source=(
            self.payment_source
            if hasattr(self, "payment_source")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"customer={_customer!r}, "
            f"payment_source={_payment_source!r}, "
            f"links={_links!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _customer=(
            self.customer
            if hasattr(self, "customer")
            else None
        )
        _payment_source=(
            self.payment_source
            if hasattr(self, "payment_source")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"customer={_customer!s}, "
            f"payment_source={_payment_source!s}, "
            f"links={_links!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
