"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class PhoneNumber(object):
    """Implementation of the 'Phone Number' model.

    The phone number, in its canonical international [E.164 numbering plan
    format](https://www.itu.int/rec/T-REC-E.164/en)., The phone number in its
    canonical international [E.164 numbering plan
    format](https://www.itu.int/rec/T-REC-E.164/en)., The phone number, in its
    canonical international [E.164 numbering plan
    format](https://www.itu.int/rec/T-REC-E.164/en)., The phone number in its
    canonical international [E.164 numbering plan
    format](https://www.itu.int/rec/T-REC-E.164/en).

    Attributes:
        national_number (str): The national number, in its canonical international
            [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en).
            The combined length of the country calling code (CC) and the national
            number must not be greater than 15 digits. The national number consists
            of a national destination code (NDC) and subscriber number (SN).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "national_number": "national_number",
    }

    def __init__(
        self,
        national_number=None,
        additional_properties=None):
        """Initialize a PhoneNumber instance."""
        # Initialize members of the class
        self.national_number = national_number

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        national_number =\
            dictionary.get("national_number")\
            if dictionary.get("national_number")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(national_number,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _national_number=self.national_number
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"national_number={_national_number!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _national_number=self.national_number
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"national_number={_national_number!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
