"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.billing_cycle import BillingCycle
from paypal.models.one_time_charge import OneTimeCharge


class Plan(object):
    """Implementation of the 'Plan' model.

    The merchant level Recurring Billing plan metadata for the Billing Agreement.

    Attributes:
        billing_cycles (List[BillingCycle]): An array of billing cycles for trial
            billing and regular billing. A plan can have at most two trial cycles and
            only one regular cycle.
        one_time_charges (OneTimeCharge): The one-time charge info at the time of
            checkout.
        name (str): Name of the recurring plan.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "billing_cycles": "billing_cycles",
        "one_time_charges": "one_time_charges",
        "name": "name",
    }

    _optionals = [
        "name",
    ]

    def __init__(
        self,
        billing_cycles=None,
        one_time_charges=None,
        name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Plan instance."""
        # Initialize members of the class
        self.billing_cycles = billing_cycles
        self.one_time_charges = one_time_charges
        if name is not APIHelper.SKIP:
            self.name = name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        billing_cycles = None
        if dictionary.get("billing_cycles") is not None:
            billing_cycles = [
                BillingCycle.from_dictionary(x)
                    for x in dictionary.get("billing_cycles")
            ]
        one_time_charges =\
            OneTimeCharge.from_dictionary(
                dictionary.get("one_time_charges"))\
                if dictionary.get("one_time_charges") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(billing_cycles,
                   one_time_charges,
                   name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _billing_cycles=self.billing_cycles
        _one_time_charges=self.one_time_charges
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"billing_cycles={_billing_cycles!r}, "
            f"one_time_charges={_one_time_charges!r}, "
            f"name={_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _billing_cycles=self.billing_cycles
        _one_time_charges=self.one_time_charges
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"billing_cycles={_billing_cycles!s}, "
            f"one_time_charges={_one_time_charges!s}, "
            f"name={_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
