"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.money import Money
from paypal.models.payee_base import PayeeBase


class PlatformFee(object):
    """Implementation of the 'Platform Fee' model.

    The platform or partner fee, commission, or brokerage fee that is associated with
    the transaction. Not a separate or isolated transaction leg from the external
    perspective. The platform fee is limited in scope and is always associated with
    the original payment for the purchase unit.

    Attributes:
        amount (Money): The currency and amount for a financial transaction, such as
            a balance or payment due.
        payee (PayeeBase): The details for the merchant who receives the funds and
            fulfills the order. The merchant is also known as the payee.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "payee": "payee",
    }

    _optionals = [
        "payee",
    ]

    def __init__(
        self,
        amount=None,
        payee=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PlatformFee instance."""
        # Initialize members of the class
        self.amount = amount
        if payee is not APIHelper.SKIP:
            self.payee = payee

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            Money.from_dictionary(
                dictionary.get("amount"))\
                if dictionary.get("amount") else None
        payee =\
            PayeeBase.from_dictionary(
                dictionary.get("payee"))\
                if "payee" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(amount,
                   payee,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=self.amount
        _payee=(
            self.payee
            if hasattr(self, "payee")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"payee={_payee!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=self.amount
        _payee=(
            self.payee
            if hasattr(self, "payee")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"payee={_payee!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
