"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.refund_status_details import (
    RefundStatusDetails,
)


class RefundStatusWithDetails(object):
    """Implementation of the 'Refund Status With Details' model.

    The refund status with details.

    Attributes:
        status (RefundStatus): The status of the refund.
        status_details (RefundStatusDetails): The details of the refund status.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "status_details": "status_details",
    }

    _optionals = [
        "status",
        "status_details",
    ]

    def __init__(
        self,
        status=APIHelper.SKIP,
        status_details=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RefundStatusWithDetails instance."""
        # Initialize members of the class
        if status is not APIHelper.SKIP:
            self.status = status
        if status_details is not APIHelper.SKIP:
            self.status_details = status_details

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        status_details =\
            RefundStatusDetails.from_dictionary(
                dictionary.get("status_details"))\
                if "status_details" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status,
                   status_details,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _status_details=(
            self.status_details
            if hasattr(self, "status_details")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"status_details={_status_details!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _status_details=(
            self.status_details
            if hasattr(self, "status_details")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"status_details={_status_details!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
