"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.participant_metadata import (
    ParticipantMetadata,
)


class RiskSupplementaryData(object):
    """Implementation of the 'Risk Supplementary Data' model.

    Additional information necessary to evaluate the risk profile of a transaction.

    Attributes:
        customer (ParticipantMetadata): Profile information of the sender or receiver.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "customer": "customer",
    }

    _optionals = [
        "customer",
    ]

    def __init__(
        self,
        customer=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RiskSupplementaryData instance."""
        # Initialize members of the class
        if customer is not APIHelper.SKIP:
            self.customer = customer

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        customer =\
            ParticipantMetadata.from_dictionary(
                dictionary.get("customer"))\
                if "customer" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(customer,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _customer=(
            self.customer
            if hasattr(self, "customer")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"customer={_customer!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _customer=(
            self.customer
            if hasattr(self, "customer")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"customer={_customer!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
