"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class SepaDebitExperienceContext1(object):
    """Implementation of the 'SEPA Debit Experience Context1' model.

    Customizes the payer experience during the approval process for the SEPA Debit
    payment.

    Attributes:
        locale (str): The [language tag](https://tools.ietf.org/html/bcp47#section-2)
            for the language in which to localize the error-related strings, such as
            messages, issues, and suggested actions. The tag is made up of the [ISO
            639-2 language
            code](https://www.loc.gov/standards/iso639-2/php/code_list.php), the
            optional [ISO-15924 script
            tag](https://www.unicode.org/iso15924/codelists.html), and the [ISO-3166
            alpha-2 country
            code](https://developer.paypal.com/api/rest/reference/country-codes/) or
            [M49 region code](https://unstats.un.org/unsd/methodology/m49/).
        return_url (str): Describes the URL.
        cancel_url (str): Describes the URL.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "return_url": "return_url",
        "cancel_url": "cancel_url",
        "locale": "locale",
    }

    _optionals = [
        "locale",
    ]

    def __init__(
        self,
        return_url=None,
        cancel_url=None,
        locale=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SepaDebitExperienceContext1 instance."""
        # Initialize members of the class
        if locale is not APIHelper.SKIP:
            self.locale = locale
        self.return_url = return_url
        self.cancel_url = cancel_url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        return_url =\
            dictionary.get("return_url")\
            if dictionary.get("return_url")\
                else None
        cancel_url =\
            dictionary.get("cancel_url")\
            if dictionary.get("cancel_url")\
                else None
        locale =\
            dictionary.get("locale")\
            if dictionary.get("locale")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(return_url,
                   cancel_url,
                   locale,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _locale=(
            self.locale
            if hasattr(self, "locale")
            else None
        )
        _return_url=self.return_url
        _cancel_url=self.cancel_url
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"locale={_locale!r}, "
            f"return_url={_return_url!r}, "
            f"cancel_url={_cancel_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _locale=(
            self.locale
            if hasattr(self, "locale")
            else None
        )
        _return_url=self.return_url
        _cancel_url=self.cancel_url
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"locale={_locale!s}, "
            f"return_url={_return_url!s}, "
            f"cancel_url={_cancel_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
