"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.sepa_debit_experience_context import (
    SepaDebitExperienceContext,
)


class SepaDebitRequest(object):
    """Implementation of the 'SEPA Debit Request' model.

    An API resource denoting a request to securely store a SEPA Debit.

    Attributes:
        experience_context (SepaDebitExperienceContext): Customizes the payer
            experience during the approval process for the SEPA Debit payment.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "experience_context": "experience_context",
    }

    _optionals = [
        "experience_context",
    ]

    def __init__(
        self,
        experience_context=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SepaDebitRequest instance."""
        # Initialize members of the class
        if experience_context is not APIHelper.SKIP:
            self.experience_context = experience_context

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        experience_context =\
            SepaDebitExperienceContext.from_dictionary(
                dictionary.get("experience_context"))\
                if "experience_context" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(experience_context,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _experience_context=(
            self.experience_context
            if hasattr(self, "experience_context")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"experience_context={_experience_context!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _experience_context=(
            self.experience_context
            if hasattr(self, "experience_context")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"experience_context={_experience_context!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
