"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.bank_request import BankRequest
from paypal.models.setup_token_request_card import (
    SetupTokenRequestCard,
)
from paypal.models.vault_apple_pay_request import (
    VaultApplePayRequest,
)
from paypal.models.vault_pay_pal_wallet_request import (
    VaultPayPalWalletRequest,
)
from paypal.models.vault_token_request import (
    VaultTokenRequest,
)
from paypal.models.vault_venmo_request import (
    VaultVenmoRequest,
)


class SetupTokenRequestPaymentSource(object):
    """Implementation of the 'Setup Token Request Payment Source' model.

    The payment method to vault with the instrument details.

    Attributes:
        card (SetupTokenRequestCard): A Resource representing a request to vault a
            Card.
        paypal (VaultPayPalWalletRequest): A resource representing a request to vault
            PayPal Wallet.
        venmo (VaultVenmoRequest): A resource representing a request to vault Venmo.
        apple_pay (VaultApplePayRequest): A resource representing a request to vault
            Apple Pay.
        token (VaultTokenRequest): The Tokenized Payment Source representing a
            Request to Vault a Token.
        bank (BankRequest): A Resource representing a request to vault a Bank used
            for ACH Debit.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "card": "card",
        "paypal": "paypal",
        "venmo": "venmo",
        "apple_pay": "apple_pay",
        "token": "token",
        "bank": "bank",
    }

    _optionals = [
        "card",
        "paypal",
        "venmo",
        "apple_pay",
        "token",
        "bank",
    ]

    def __init__(
        self,
        card=APIHelper.SKIP,
        paypal=APIHelper.SKIP,
        venmo=APIHelper.SKIP,
        apple_pay=APIHelper.SKIP,
        token=APIHelper.SKIP,
        bank=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SetupTokenRequestPaymentSource instance."""
        # Initialize members of the class
        if card is not APIHelper.SKIP:
            self.card = card
        if paypal is not APIHelper.SKIP:
            self.paypal = paypal
        if venmo is not APIHelper.SKIP:
            self.venmo = venmo
        if apple_pay is not APIHelper.SKIP:
            self.apple_pay = apple_pay
        if token is not APIHelper.SKIP:
            self.token = token
        if bank is not APIHelper.SKIP:
            self.bank = bank

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        card =\
            SetupTokenRequestCard.from_dictionary(
                dictionary.get("card"))\
                if "card" in dictionary.keys()\
                else APIHelper.SKIP
        paypal =\
            VaultPayPalWalletRequest.from_dictionary(
                dictionary.get("paypal"))\
                if "paypal" in dictionary.keys()\
                else APIHelper.SKIP
        venmo =\
            VaultVenmoRequest.from_dictionary(
                dictionary.get("venmo"))\
                if "venmo" in dictionary.keys()\
                else APIHelper.SKIP
        apple_pay =\
            VaultApplePayRequest.from_dictionary(
                dictionary.get("apple_pay"))\
                if "apple_pay" in dictionary.keys()\
                else APIHelper.SKIP
        token =\
            VaultTokenRequest.from_dictionary(
                dictionary.get("token"))\
                if "token" in dictionary.keys()\
                else APIHelper.SKIP
        bank =\
            BankRequest.from_dictionary(
                dictionary.get("bank"))\
                if "bank" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(card,
                   paypal,
                   venmo,
                   apple_pay,
                   token,
                   bank,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _paypal=(
            self.paypal
            if hasattr(self, "paypal")
            else None
        )
        _venmo=(
            self.venmo
            if hasattr(self, "venmo")
            else None
        )
        _apple_pay=(
            self.apple_pay
            if hasattr(self, "apple_pay")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _bank=(
            self.bank
            if hasattr(self, "bank")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!r}, "
            f"paypal={_paypal!r}, "
            f"venmo={_venmo!r}, "
            f"apple_pay={_apple_pay!r}, "
            f"token={_token!r}, "
            f"bank={_bank!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _paypal=(
            self.paypal
            if hasattr(self, "paypal")
            else None
        )
        _venmo=(
            self.venmo
            if hasattr(self, "venmo")
            else None
        )
        _apple_pay=(
            self.apple_pay
            if hasattr(self, "apple_pay")
            else None
        )
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _bank=(
            self.bank
            if hasattr(self, "bank")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!s}, "
            f"paypal={_paypal!s}, "
            f"venmo={_venmo!s}, "
            f"apple_pay={_apple_pay!s}, "
            f"token={_token!s}, "
            f"bank={_bank!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
