"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.pay_pal_payment_token import (
    PayPalPaymentToken,
)
from paypal.models.setup_token_response_card import (
    SetupTokenResponseCard,
)
from paypal.models.venmo_payment_token import (
    VenmoPaymentToken,
)


class SetupTokenResponsePaymentSource(object):
    """Implementation of the 'Setup Token Response Payment Source' model.

    The setup payment method details.

    Attributes:
        card (SetupTokenResponseCard): The model property of type
            SetupTokenResponseCard.
        paypal (PayPalPaymentToken): Full representation of a PayPal Payment Token.
        venmo (VenmoPaymentToken): Full representation of a Venmo Payment Token.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "card": "card",
        "paypal": "paypal",
        "venmo": "venmo",
    }

    _optionals = [
        "card",
        "paypal",
        "venmo",
    ]

    def __init__(
        self,
        card=APIHelper.SKIP,
        paypal=APIHelper.SKIP,
        venmo=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SetupTokenResponsePaymentSource instance."""
        # Initialize members of the class
        if card is not APIHelper.SKIP:
            self.card = card
        if paypal is not APIHelper.SKIP:
            self.paypal = paypal
        if venmo is not APIHelper.SKIP:
            self.venmo = venmo

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        card =\
            SetupTokenResponseCard.from_dictionary(
                dictionary.get("card"))\
                if "card" in dictionary.keys()\
                else APIHelper.SKIP
        paypal =\
            PayPalPaymentToken.from_dictionary(
                dictionary.get("paypal"))\
                if "paypal" in dictionary.keys()\
                else APIHelper.SKIP
        venmo =\
            VenmoPaymentToken.from_dictionary(
                dictionary.get("venmo"))\
                if "venmo" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(card,
                   paypal,
                   venmo,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _paypal=(
            self.paypal
            if hasattr(self, "paypal")
            else None
        )
        _venmo=(
            self.venmo
            if hasattr(self, "venmo")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!r}, "
            f"paypal={_paypal!r}, "
            f"venmo={_venmo!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _paypal=(
            self.paypal
            if hasattr(self, "paypal")
            else None
        )
        _venmo=(
            self.venmo
            if hasattr(self, "venmo")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!s}, "
            f"paypal={_paypal!s}, "
            f"venmo={_venmo!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
