from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel
from .phone_with_type import PhoneWithType, PhoneWithTypeDict


class SubscriptionCustomerInformation(SdkBaseModel):
    """The details about a customer in PayPal's system of record."""

    id: Optional[str] = UNSET
    """The unique ID for a customer generated by PayPal."""

    email_address: Optional[str] = UNSET
    """The internationalized email address. Note: Up to 64 characters are allowed before and 255 characters are allowed
    after the @ sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern
    verifies that an unquoted @ sign exists."""

    phone: Optional[PhoneWithType] = UNSET
    """The phone information."""


class SubscriptionCustomerInformationDict(TypedDict):
    id: NotRequired[str]
    email_address: NotRequired[str]
    phone: NotRequired[PhoneWithType | PhoneWithTypeDict]
