"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.card_supplementary_data import (
    CardSupplementaryData,
)
from paypal.models.risk_supplementary_data import (
    RiskSupplementaryData,
)


class SupplementaryData(object):
    """Implementation of the 'Supplementary Data' model.

    Supplementary data about a payment. This object passes information that can be
    used to improve risk assessments and processing costs, for example, by providing
    Level 2 and Level 3 payment data.

    Attributes:
        card (CardSupplementaryData): Merchants and partners can add Level 2 and 3
            data to payments to reduce risk and payment processing costs. For more
            information about processing payments, see checkout or multiparty
            checkout.
        risk (RiskSupplementaryData): Additional information necessary to evaluate
            the risk profile of a transaction.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "card": "card",
        "risk": "risk",
    }

    _optionals = [
        "card",
        "risk",
    ]

    def __init__(
        self,
        card=APIHelper.SKIP,
        risk=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SupplementaryData instance."""
        # Initialize members of the class
        if card is not APIHelper.SKIP:
            self.card = card
        if risk is not APIHelper.SKIP:
            self.risk = risk

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        card =\
            CardSupplementaryData.from_dictionary(
                dictionary.get("card"))\
                if "card" in dictionary.keys()\
                else APIHelper.SKIP
        risk =\
            RiskSupplementaryData.from_dictionary(
                dictionary.get("risk"))\
                if "risk" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(card,
                   risk,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _risk=(
            self.risk
            if hasattr(self, "risk")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!r}, "
            f"risk={_risk!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _card=(
            self.card
            if hasattr(self, "card")
            else None
        )
        _risk=(
            self.risk
            if hasattr(self, "risk")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"card={_card!s}, "
            f"risk={_risk!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
