"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.money import Money


class TaxAmount(object):
    """Implementation of the 'Tax Amount' model.

    The tax levied by a government on the purchase of goods or services.

    Attributes:
        tax_amount (Money): The currency and amount for a financial transaction, such
            as a balance or payment due.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tax_amount": "tax_amount",
    }

    _optionals = [
        "tax_amount",
    ]

    def __init__(
        self,
        tax_amount=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TaxAmount instance."""
        # Initialize members of the class
        if tax_amount is not APIHelper.SKIP:
            self.tax_amount = tax_amount

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tax_amount =\
            Money.from_dictionary(
                dictionary.get("tax_amount"))\
                if "tax_amount" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(tax_amount,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _tax_amount=(
            self.tax_amount
            if hasattr(self, "tax_amount")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"tax_amount={_tax_amount!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _tax_amount=(
            self.tax_amount
            if hasattr(self, "tax_amount")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"tax_amount={_tax_amount!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
