"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class Taxes(object):
    """Implementation of the 'Taxes' model.

    The tax details.

    Attributes:
        percentage (str): The percentage, as a fixed-point, signed decimal number.
            For example, define a 19.99% interest rate as `19.99`.
        inclusive (bool): Indicates whether the tax was already included in the
            billing amount.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "percentage": "percentage",
        "inclusive": "inclusive",
    }

    _optionals = [
        "inclusive",
    ]

    def __init__(
        self,
        percentage=None,
        inclusive=True,
        additional_properties=None):
        """Initialize a Taxes instance."""
        # Initialize members of the class
        self.percentage = percentage
        self.inclusive = inclusive

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        percentage =\
            dictionary.get("percentage")\
            if dictionary.get("percentage")\
                else None
        inclusive =\
            dictionary.get("inclusive")\
            if dictionary.get("inclusive")\
                else True

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(percentage,
                   inclusive,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _percentage=self.percentage
        _inclusive=(
            self.inclusive
            if hasattr(self, "inclusive")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"percentage={_percentage!r}, "
            f"inclusive={_inclusive!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _percentage=self.percentage
        _inclusive=(
            self.inclusive
            if hasattr(self, "inclusive")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"percentage={_percentage!s}, "
            f"inclusive={_inclusive!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
