"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class UniversalProductCode(object):
    """Implementation of the 'Universal Product Code' model.

    The Universal Product Code of the item.

    Attributes:
        mtype (UpcType): The Universal Product Code type.
        code (str): The UPC product code of the item.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "code": "code",
    }

    def __init__(
        self,
        mtype=None,
        code=None,
        additional_properties=None):
        """Initialize a UniversalProductCode instance."""
        # Initialize members of the class
        self.mtype = mtype
        self.code = code

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   code,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _code=self.code
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"code={_code!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _code=self.code
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"code={_code!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
