from __future__ import annotations

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel
from .name import Name, NameDict


class VaultCustomer(SdkBaseModel):
    """This object represents a merchant’s customer, allowing them to store contact details, and track all payments
    associated with the same customer."""

    id: Optional[str] = UNSET
    """The unique ID for a customer generated by PayPal."""

    name: Optional[Name] = UNSET
    """The name of the party."""


class VaultCustomerDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[Name | NameDict]
