from __future__ import annotations

from typing import Any

from typing_extensions import NotRequired, TypedDict

from ..core import UNSET, Optional, SdkBaseModel


class VaultResponseCustomer(SdkBaseModel):
    """This object defines a customer in your system. Use it to manage customer profiles, save payment methods and
    contact details."""

    id: Optional[str] = UNSET
    """The unique ID for a customer generated by PayPal."""

    merchant_customer_id: Optional[str] = UNSET
    """Merchants and partners may already have a data-store where their customer information is persisted. Use
    merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer."""

    links: Optional[list[Any]] = UNSET
    """DEPRECATED. This field is DEPRECATED."""


class VaultResponseCustomerDict(TypedDict):
    id: NotRequired[str]
    merchant_customer_id: NotRequired[str]
    links: NotRequired[list[Any]]
