"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper


class VaultInstructionBase(object):
    """Implementation of the 'Vault Instruction Base' model.

    Basic vault instruction specification that can be extended by specific payment
    sources that supports vaulting.

    Attributes:
        store_in_vault (StoreInVaultInstruction): Defines how and when the payment
            source gets vaulted.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "store_in_vault": "store_in_vault",
    }

    _optionals = [
        "store_in_vault",
    ]

    def __init__(
        self,
        store_in_vault=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a VaultInstructionBase instance."""
        # Initialize members of the class
        if store_in_vault is not APIHelper.SKIP:
            self.store_in_vault = store_in_vault

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        store_in_vault =\
            dictionary.get("store_in_vault")\
            if dictionary.get("store_in_vault")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(store_in_vault,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _store_in_vault=(
            self.store_in_vault
            if hasattr(self, "store_in_vault")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"store_in_vault={_store_in_vault!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _store_in_vault=(
            self.store_in_vault
            if hasattr(self, "store_in_vault")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"store_in_vault={_store_in_vault!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
