"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypal.api_helper import APIHelper
from paypal.models.venmo_vault_response import (
    VenmoVaultResponse,
)


class VenmoWalletAttributesResponse(object):
    """Implementation of the 'Venmo Wallet Attributes Response' model.

    Additional attributes associated with the use of a Venmo Wallet.

    Attributes:
        vault (VenmoVaultResponse): The details about a saved venmo payment source.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "vault": "vault",
    }

    _optionals = [
        "vault",
    ]

    def __init__(
        self,
        vault=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a VenmoWalletAttributesResponse instance."""
        # Initialize members of the class
        if vault is not APIHelper.SKIP:
            self.vault = vault

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        vault =\
            VenmoVaultResponse.from_dictionary(
                dictionary.get("vault"))\
                if "vault" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(vault,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _vault=(
            self.vault
            if hasattr(self, "vault")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"vault={_vault!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _vault=(
            self.vault
            if hasattr(self, "vault")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"vault={_vault!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
