"""paypal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from paypal.apis.base_api import BaseApi
from paypal.apis.oauth_authorization_api import (
    OauthAuthorizationApi,
)
from paypal.apis.orders_api import OrdersApi
from paypal.apis.payments_api import PaymentsApi
from paypal.apis.subscriptions_api import SubscriptionsApi
from paypal.apis.transaction_search_api import (
    TransactionSearchApi,
)
from paypal.apis.vault_api import VaultApi
from paypal.configuration import (
    Configuration,
    Environment,
)
from paypal.http.auth.oauth_2 import Oauth2


class PaypalClient(object):
    """Client that provide access to the PaypalClient APIs."""

    @LazyProperty
    def subscriptions(self):
        """Provide access to the SubscriptionsApi endpoints."""
        return SubscriptionsApi(self.global_configuration)

    @LazyProperty
    def orders(self):
        """Provide access to the OrdersApi endpoints."""
        return OrdersApi(self.global_configuration)

    @LazyProperty
    def payments(self):
        """Provide access to the PaymentsApi endpoints."""
        return PaymentsApi(self.global_configuration)

    @LazyProperty
    def vault(self):
        """Provide access to the VaultApi endpoints."""
        return VaultApi(self.global_configuration)

    @LazyProperty
    def transaction_search(self):
        """Provide access to the TransactionSearchApi endpoints."""
        return TransactionSearchApi(self.global_configuration)

    @LazyProperty
    def oauth_authorization(self):
        """Provide access to the OauthAuthorizationApi endpoints."""
        return OauthAuthorizationApi(self.global_configuration)

    @property
    def oauth_2(self):
        """Provide access to the Oauth2 auth manager."""
        return self.auth_managers["Oauth2"]

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 client_credentials_auth_credentials=None, config=None):
        """Initialize a new instance of PaypalClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            client_credentials_auth_credentials=client_credentials_auth_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

        self.auth_managers = {
            "Oauth2": Oauth2(self.config.client_credentials_auth_credentials,
                             self.global_configuration),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            PaypalClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
